### ISSUE TITLE
Image export cropped from large screen size

### ISSUE THREAD

**Issue by ollyburren** [D-I-L/django-chicpea#12]
If I attempt to export an image when browser is full screen - the resultant image is cropped. If I resize browser and reload (which alters size of images) then exported image is no longer cropped. Using Chrome Version 40.0.2214.94 (64-bit) on Linux XXXX 3.2.0-87-generic #125-Ubuntu SMP Fri Jun 19 08:25:10 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by tottlefields** [comment]
PDF/PNG export code updated to work out exported image size based on svg size.
