### ISSUE TITLE
1:247140777-247846258 region causes a crash when swapping association dataset

### ISSUE THREAD

**Issue by ollyburren** [D-I-L/django-chicpea#16]
On  hic.immunobase.org search for the above region. Now try and alter association statistics. This causes a javascript error to be thrown 'Uncaught TypeError: Cannot read property 'rend' of undefined'

**Comment by tottlefields** [comment]
Created a sensible error message and response rather than bombing out; Fixed error of region-based searches and switching snp tracks.

**Comment by ollyburren** [comment]
reopening see Tims Bug #41

**Comment by tottlefields** [comment]
Fix for snp tracks re-committed as seems to have been lost along the way somehow. Error now reports sensible error message.
