### ISSUE TITLE
Part of circular scale missing at top

### ISSUE THREAD

**Issue by tcarver** [D-I-L/django-chicpea#34]
Firefox, search for PAX6. Looks likes when the height is restricted you miss the top of the scale.

![chicp_pax6_ff](https://cloud.githubusercontent.com/assets/866299/10935869/d8ffc094-82e0-11e5-8ba8-63ce300ffa12.png)

**Comment by tottlefields** [comment]
Added a padding to the svg div; corrected svg export to cope with overlap of titles and scale
