### ISSUE TITLE
TypeError: data.meta is undefined

### ISSUE THREAD

**Issue by tcarver** [D-I-L/django-chicpea#41]
Firefox: I get this error when switching to Javierre after searching for rs777502657

TypeError: data.meta is undefined
var totalBP = data.meta.rend - data.meta.rstart;
/chicp/ (line 561, col 15)

**Comment by ollyburren** [comment]
I get similar error if I search for  rs16918479 in chrome and then switch to Javierre. 

Uncaught TypeError: Cannot read property 'rend' of undefined

**Comment by tottlefields** [comment]
Can confirm in safari too...
TypeError: undefined is not an object (evaluating 'data.meta.rend')

**Comment by tottlefields** [comment]
Fix for snp tracks re-committed as seems to have been lost along the way somehow. Error now reports sensible error message.
