### ISSUE TITLE
admin interface visible

### ISSUE THREAD

**Issue by tcarver** [D-I-L/django-chicpea#43]
https://www.chicp.org/admin/login/?next=/admin/

**Comment by tottlefields** [comment]
Will be removed once we no longer need it.

**Comment by tottlefields** [comment]
@premanand17 did we figure a way to remove the admin interface for people but still have access ourselves?

**Comment by premanand17** [comment]
The workaround is to mask the default /admin url, with following settings in urls.py

url(r'^{}/admin/'.format(settings.ADMIN_URL_PATH), include(admin.site.urls)),

add the following attribute in secret_settings.py
ADMIN_URL_PATH = 'XXXXXXX'

so the url becomes, http://prem-rh1:9000/XXXXXX/admin, which obfuscates the default admin url.

Pointer (Thnx to Tim): http://www.jw.pe/blog/post/security-through-obscurity-django-admin-interface/

**Comment by tottlefields** [comment]
Updated on live site and can confirm that the /admin path is no longer found.  Thanks @premanand17 .
