### ISSUE TITLE
register new user

### ISSUE THREAD

**Issue by tcarver** [D-I-L/django-chicpea#44]
Tried to register but it says : User with this Email address already exists. This should be bold and in red.

![chicp](https://cloud.githubusercontent.com/assets/866299/10936944/af59e114-82e7-11e5-9bf0-49785aba3b13.png)

**Comment by premanand17** [comment]
Fixed and committed

![image](https://cloud.githubusercontent.com/assets/10760269/10973396/2c163566-83d5-11e5-8abc-41db5ee87094.png)
