### ISSUE TITLE
Password reset leads to django admin page

### ISSUE THREAD

**Issue by tcarver** [D-I-L/django-chicpea#45]
Password reset when completed lands on this page rather than the home:
https://www.chicp.org/accounts/user/password/done/

![chico](https://cloud.githubusercontent.com/assets/866299/10937031/26df13c6-82e8-11e5-8d65-c8f687ed7d51.png)

**Comment by premanand17** [comment]
Fixed and committed. Goes now to the site page with confirmation message an login link.

![image](https://cloud.githubusercontent.com/assets/10760269/10970988/c5cb7308-83c9-11e5-8753-90a910f4d575.png)
