### ISSUE TITLE
Search for Y_RNA gives strange image

### ISSUE THREAD

**Issue by premanand17** [D-I-L/django-chicpea#53]
Y_RNA takes long to search,  gives strange image and gives message 'Entity too large'

**Comment by premanand17** [comment]
Trying to export as SVG image, gives

Request Entity Too Large
The requested resource
/chicp/download
 does not allow request data with POST requests, or the amount of data provided in the request exceeds the capacity limit.

**Comment by ollyburren** [comment]
Good spot these are ubiquitous in the genome and actually quite interesting; perhaps a filter for genes that have more than a certain number of TSS/bait fragments ?

**Comment by tottlefields** [comment]
I was thinking of a search result list?

**Comment by tottlefields** [comment]
Built a results table to show all matches when get mutiple results for a search (eg Y_RNA, FOXP3).  @tcarver suggested restricting results table list to only those that have hits in the currently selected dataset.
